INSERT INTO locales (nombre_completo, direccion_completa, metros_cuadrados, precio_alquiler) VALUES ('Tienda de Ropa', 'Calle Falsa 123, Sevilla', 85, 1200.50);
INSERT INTO locales (nombre_completo, direccion_completa, metros_cuadrados, precio_alquiler) VALUES ('Cafetería Central', 'Avenida Principal 45, Madrid', 60, 950.00);
INSERT INTO locales (nombre_completo, direccion_completa, metros_cuadrados, precio_alquiler) VALUES ('Oficina de Abogados', 'Plaza Mayor 1, Barcelona', 120, 2100.00);
INSERT INTO locales (nombre_completo, direccion_completa, metros_cuadrados, precio_alquiler) VALUES ('Peluquería Lola', 'Calle del Pez 8, Valencia', 45, 750.75);
INSERT INTO locales (nombre_completo, direccion_completa, metros_cuadrados, precio_alquiler) VALUES ('Gimnasio Fitness', 'Ronda de Dalt 200, Barcelona', 250, 3500.00);
INSERT INTO locales (nombre_completo, direccion_completa, metros_cuadrados, precio_alquiler) VALUES ('Librería El Saber', 'Calle Libreros 10, Salamanca', 70, 890.00);
INSERT INTO locales (nombre_completo, direccion_completa, metros_cuadrados, precio_alquiler) VALUES ('Restaurante Mediterráneo', 'Paseo Marítimo 5, Málaga', 180, 2800.00);
INSERT INTO locales (nombre_completo, direccion_completa, metros_cuadrados, precio_alquiler) VALUES ('Clínica Dental', 'Calle de la Salud 3, Bilbao', 95, 1500.25);
INSERT INTO locales (nombre_completo, direccion_completa, metros_cuadrados, precio_alquiler) VALUES ('Estudio de Yoga', 'Travesía del Silencio 7, Granada', 55, 600.00);
INSERT INTO locales (nombre_completo, direccion_completa, metros_cuadrados, precio_alquiler) VALUES ('Tienda de Electrónica', 'Centro Comercial Nevada, Granada', 110, 1900.00);
