INSERT INTO preguntas (tema, dificultad, enuncioado, solucion) VALUES ('naturaleza', 1, '¿Los árboles producen oxígeno durante el día?', TRUE);
INSERT INTO preguntas (tema, dificultad, enuncioado, solucion) VALUES ('naturaleza', 2, '¿Las abejas son mamíferos?', FALSE);
INSERT INTO preguntas (tema, dificultad, enuncioado, solucion) VALUES ('naturaleza', 3, '¿Las plantas realizan la fotosíntesis usando dióxido de carbono?', TRUE);
INSERT INTO preguntas (tema, dificultad, enuncioado, solucion) VALUES ('matematicas', 1, '¿5 + 3 es igual a 8?', TRUE);
INSERT INTO preguntas (tema, dificultad, enuncioado, solucion) VALUES ('matematicas', 2, '¿El doble de 7 es 15?', FALSE);
INSERT INTO preguntas (tema, dificultad, enuncioado, solucion) VALUES ('matematicas', 3, '¿La raíz cuadrada de 81 es 9?', TRUE);
INSERT INTO preguntas (tema, dificultad, enuncioado, solucion) VALUES ('geografia', 1, '¿Francia está en Europa?', TRUE);
INSERT INTO preguntas (tema, dificultad, enuncioado, solucion) VALUES ('geografia', 2, '¿El río Amazonas pasa por México?', FALSE);
INSERT INTO preguntas (tema, dificultad, enuncioado, solucion) VALUES ('geografia', 3, '¿El Monte Everest se encuentra en Asia?', TRUE);
INSERT INTO preguntas (tema, dificultad, enuncioado, solucion) VALUES ('historia', 1, '¿Cristóbal Colón llegó a América en 1492?', TRUE);
INSERT INTO preguntas (tema, dificultad, enuncioado, solucion) VALUES ('historia', 2, '¿El Imperio Romano cayó antes del Imperio Griego?', FALSE);
INSERT INTO preguntas (tema, dificultad, enuncioado, solucion) VALUES ('historia', 3, '¿La Primera Guerra Mundial comenzó en 1914?', TRUE);