INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿Es la capital de Francia, París?', true);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿El agua hierve a 90 grados Celsius?', false);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿La tierra es plana?', false);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿Los humanos tienen 4 pulmones?', false);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿El sol es una estrella?', true);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿La luna es más grande que la tierra?', false);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿Java es un lenguaje de programación?', true);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿Spring es un framework de Python?', false);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿H2 es una base de datos en memoria?', true);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿SQL es un lenguaje para consultar bases de datos?', true);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿El Océano Pacífico es el más grande del mundo?', true);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿Los pingüinos pueden volar?', false);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿El diamante es el material natural más duro?', true);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿Australia es un continente y un país?', true);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿El cuerpo humano tiene 206 huesos?', true);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿Venus es el planeta más cercano al sol?', false);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿El código binario se compone solo de 0s y 1s?', true);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿El tomate es una verdura?', false);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿La Gran Muralla China es visible desde la luna?', false);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿JavaScript es lo mismo que Java?', false);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿El cerebro humano deja de crecer a los 18 años?', false);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿Un año luz mide tiempo?', false);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿Los camaleones cambian de color para camuflarse?', true);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿El Monte Everest es la montaña más alta del mundo?', true);
INSERT INTO pregunta (enunciado, respuesta) VALUES ('¿Thymeleaf es un motor de plantillas del lado del cliente?', false);
